@echo off
cd /d "%~dp0"
IF EXIST venv\Scripts\activate.bat call venv\Scripts\activate.bat
echo [Autopilot] Running Black...
black --check core tests
echo [Autopilot] Running Ruff...
ruff check core tests
echo [Autopilot] Running mypy...
mypy core --ignore-missing-imports
echo [Autopilot] Running pytest...
pytest tests -v --tb=short
